routes/web.php
<?php

use App\Http\Controllers\RoomBillController;
use App\Http\Controllers\RoomCategoriesController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\RoomStatusController;
use App\Http\Controllers\UserController;
use App\Models\RoomBill;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/denies', [App\Http\Controllers\HomeController::class, 'denies'])->name('denies');

/*------ Admin ------*/
Route::prefix('admin')->middleware('auth')->group(function () {

    /*------ Route Users ------*/
    Route::prefix('users')->name('users.')->group(function () {
        $class = UserController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{user}', [$class, 'show'])->name('show');
        Route::put('/{user}', [$class, 'update'])->name('update');
        Route::delete('/{user}', [$class, 'destroy'])->name('destroy');
        Route::get('/{user}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route RoomCategory ------*/
    Route::prefix('categories')->name('categories.')->group(function () {
        $class = RoomCategoriesController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomCategories}', [$class, 'show'])->name('show');
        Route::put('/{roomCategories}', [$class, 'update'])->name('update');
        Route::delete('/{roomCategories}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomCategories}/edit', [$class, 'edit'])->name('edit');
        Route::get('/{roomCategories}/select', [$class, 'SelectCategoryOrder'])->name('select');
    });

    /*------ Route Room ------*/
    Route::prefix('rooms')->name('rooms.')->group(function () {
        $class = RoomController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{room}', [$class, 'show'])->name('show');
        Route::put('/{room}', [$class, 'update'])->name('update');
        Route::delete('/{room}', [$class, 'destroy'])->name('destroy');
        Route::get('/{room}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's status ------*/
    Route::prefix('status')->name('status.')->group(function () {
        $class = RoomStatusController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomStatus}', [$class, 'show'])->name('show');
        Route::put('/{roomStatus}', [$class, 'update'])->name('update');
        Route::delete('/{roomStatus}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomStatus}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's order ------*/
    Route::prefix('bills')->name('bills.')->group(function () {
        $class = RoomBillController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomBill}', [$class, 'show'])->name('show');
        Route::put('/{roomBill}', [$class, 'update'])->name('update');
        Route::delete('/{roomBill}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomBill}/edit', [$class, 'edit'])->name('edit');
    });
});

app/Http/Controllers/RoomCategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRoomCategoryRequest;
use App\Http\Requests\UpdateRoomCategoryRequest;
use App\Models\RoomBill;
use App\Models\RoomCategories;
use App\Rules\StrLengthRule;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class RoomCategoriesController extends Controller
{
    protected $roomCategories;

    public function __construct(RoomCategories $roomCategories)
    {
        $this->roomCategories = $roomCategories;
        //$this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roomCategories = $this->roomCategories->search($request->all());
        return view('AdminPage.room_categories.index', compact('roomCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('AdminPage.room_categories.create');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function SelectCategoryOrder(RoomCategories $roomCategories)
    {
        $bills = RoomBill::all();
        return view('AdminPage.room_bills.selected', compact('bills', 'roomCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoomCategoryRequest $request)
    {
        $this->roomCategories->store($request);
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\RoomCategories  $roomCategories
     * @return \Illuminate\Http\Response
     */
    public function show(RoomCategories $roomCategories)
    {
        return view('AdminPage.room_categories.show')->with([
            'roomCategories' => $roomCategories,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\RoomCategories  $roomCategories
     * @return \Illuminate\Http\Response
     */
    public function edit(RoomCategories $roomCategories)
    {
        return view("AdminPage.room_categories.edit")->with([
            'roomCategories' => $roomCategories,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\RoomCategories  $roomCategories
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, RoomCategories $roomCategories)
    {
        $this->validate($request, [
            'category_name' => [
                'required',
                'alpha_dash',
                Rule::unique('room_categories')->ignore($roomCategories),
                new StrLengthRule()
            ],
            'description' => 'required|min:6|max:255',
            'price' => 'numeric|min:100|max:2000',
        ]);
        $roomCategories->updateCategory($request, $roomCategories);
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\RoomCategories  $roomCategories
     * @return \Illuminate\Http\Response
     */
    public function destroy(RoomCategories $roomCategories)
    {
        $path = public_path().'/images/room_categories/' . $roomCategories->images;
        $roomCategories->deleteFile($path);
        $roomCategories->delete();
        return redirect()->route('categories.index');
    }
}

resources/views/AdminPage/room_categories/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Create New Room Category') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('categories.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Category Name') }}</label>
                            <div class="col-md-6">
                                <input id="category_name" value="{{ old('category_name') }}" name="category_name" type="text" class="form-control @error('category_name') is-invalid @enderror" >
                                @error('category_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>
                            <div class="col-md-6">
                                <input id="description" value="{{ old('description') }}" name="description" type="text" class="form-control @error('description') is-invalid @enderror" >
                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Images') }}</label>
                            <div class="col-md-6">
                                <input id="images" type="file" name="images" class="form-control">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>
                            <div class="col-md-6">
                                <input id="price" value="{{ old('price') }}" name="price" type="text" class="form-control @error('price') is-invalid @enderror" >
                                @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/room_categories/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Edit Room Category {{$roomCategories->id}}</div>

                <div class="card-body">
                    <form action="{{ route('categories.update', $roomCategories) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Category Name</label>
                            <div class="col-md-6">
                                <input id="category_name" name="category_name" value="{{ $roomCategories->category_name }}" type="text" class="form-control @error('category_name') is-invalid @enderror" >
                                @error('category_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Description</label>
                            <div class="col-md-6">
                                <input id="description" name="description" value="{{ $roomCategories->description }}" type="text" class="form-control @error('description') is-invalid @enderror" >
                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Images</label>
                            <div class="col-md-6">
                                <input id="images" type="file" name="images" class="form-control" value="{{ $roomCategories->getImage() }}" autofocus>
                                <td><img src="{{ $roomCategories->getImage() }}" alt="{{ $roomCategories->name }}" class="image-show"></td>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Price</label>
                            <div class="col-md-6">
                                <input id="price" name="price" value="{{ $roomCategories->price }}" type="text" class="form-control @error('price') is-invalid @enderror" >
                                @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/room_categories/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">

        <div class="col-md-12">
            <h1 class="mt-4">Room Categories</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Welcome to Room Categories !!</li>
            </ol>
            <div class="card">
                <div class="card-header">
                    @room_manager
                    <a href="{{ route('categories.create') }}" class="btn btn-primary">Create New Room Categories</a>
                    @endif
                </div>
                <form action="{{ route('categories.index') }}" method="GET" class="md-3 d-flex">
                    <select name="sort_by_price">
                        <option value="">Sort by price</option>
                        <option name="price" value="ascending">Ascending</option>
                        <option name="price" value="descending">Descending</option>
                    </select>

                    <input type="text" class="form-control" name="key" value="{{request('key')}}" placeholder="Enter Room Category">
                    <input type="text" class="form-control" placeholder="Enter number per page" name="number" value="{{ request('number') }}">
                    
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Description</th>
                            <th scope="col">Images</th>
                            <th scope="col">Price</th>
                            <th scope="col">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($roomCategories as $category)
                            <tr>
                                <th scope="row">{{$category->id}}</th>
                                <td>{{$category->category_name}}</td>
                                <td>{{$category->description}}</td>
                                <td><img src="{{ $category->getImage() }}" alt="{{ $category->name }}" class="image-show"></td>
                                <td>{{$category->price}} $</td>
                                <td>
                                    <a href="{{ route('categories.show', $category->id) }}"><button type="button" class="btn btn-success">DETAIL</button></a>
                                    @room_manager
                                    <a href="{{ route('categories.edit', $category->id) }}"><button type="button" class="btn btn-warning">EDIT</button>
                                    <form action="{{ route('categories.destroy', $category) }}" method="POST" class="float-left">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">DELETE</button>
                                    </form>
                                    @endif
                                </td>
                              </tr>
                            @endforeach
                        </tbody>
                      </table>
                      {{$roomCategories->appends(request()->only('key','number','sort_by_price'))->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/room_categories/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <br>
  <div class="container-fliud"> 
   <div class="wrapper row"> 
    <div class="preview col-md-6">
      <img src="{{ $roomCategories->getImage() }}" alt="{{ $roomCategories->name }}" class="imaged">
    </div> 
    <div class="details col-md-3"> 
     <h3 class="">Category: {{$roomCategories->category_name}}</h3> 
     <div class="rating"> 
      <div class="stars"> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> 
      </div>
    </div>
    <br>
    <h4>Description</h2>
     <p class="product-description">{{$roomCategories->description}}</p>
     <br>
     <h4 class="price">Price for 1 day: {{$roomCategories->price}}$</h4> 
     <a href="{{route('categories.select', $roomCategories->id)}}"><button type="button" class="btn btn-danger">Order</button></a>
    </div> 
   </div> 
  </div> 
</div> 
<!-- <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Room Categories {{$roomCategories->id}}</div>

                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Description</th>
                            <th scope="col">Images</th>
                            <th scope="col">Price</th>
                            @client
                            <th scope="col">Action</th>
                            @endif
                          </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">{{$roomCategories->id}}</th>
                                <td>{{$roomCategories->category_name}}</td>
                                <td>{{$roomCategories->description}}</td>
                                <td><img src="{{ $roomCategories->getImage() }}" alt="{{ $roomCategories->name }}" class="image-show"></td>
                                <td>{{$roomCategories->price}}</td>
                                <td>
                                <a href="{{route('categories.select', $roomCategories->id)}}"><button type="button" class="btn btn-danger">Order</button></a>
                                </td>
                              </tr>
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div> -->
@endsection