routes/web.php
<?php

use App\Http\Controllers\RoomBillController;
use App\Http\Controllers\RoomCategoriesController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\RoomStatusController;
use App\Http\Controllers\UserController;
use App\Models\RoomBill;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/denies', [App\Http\Controllers\HomeController::class, 'denies'])->name('denies');

/*------ Admin ------*/
Route::prefix('admin')->middleware('auth')->group(function () {

    /*------ Route Users ------*/
    Route::prefix('users')->name('users.')->group(function () {
        $class = UserController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{user}', [$class, 'show'])->name('show');
        Route::put('/{user}', [$class, 'update'])->name('update');
        Route::delete('/{user}', [$class, 'destroy'])->name('destroy');
        Route::get('/{user}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route RoomCategory ------*/
    Route::prefix('categories')->name('categories.')->group(function () {
        $class = RoomCategoriesController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomCategories}', [$class, 'show'])->name('show');
        Route::put('/{roomCategories}', [$class, 'update'])->name('update');
        Route::delete('/{roomCategories}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomCategories}/edit', [$class, 'edit'])->name('edit');
        Route::get('/{roomCategories}/select', [$class, 'SelectCategoryOrder'])->name('select');
    });

    /*------ Route Room ------*/
    Route::prefix('rooms')->name('rooms.')->group(function () {
        $class = RoomController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{room}', [$class, 'show'])->name('show');
        Route::put('/{room}', [$class, 'update'])->name('update');
        Route::delete('/{room}', [$class, 'destroy'])->name('destroy');
        Route::get('/{room}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's status ------*/
    Route::prefix('status')->name('status.')->group(function () {
        $class = RoomStatusController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomStatus}', [$class, 'show'])->name('show');
        Route::put('/{roomStatus}', [$class, 'update'])->name('update');
        Route::delete('/{roomStatus}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomStatus}/edit', [$class, 'edit'])->name('edit');
    });

    /*------ Route Room's order ------*/
    Route::prefix('bills')->name('bills.')->group(function () {
        $class = RoomBillController::class;
        Route::get('/', [$class, 'index'])->name('index');
        Route::get('/create', [$class, 'create'])->name('create');
        Route::post('/', [$class, 'store'])->name('store');
        Route::get('/{roomBill}', [$class, 'show'])->name('show');
        Route::put('/{roomBill}', [$class, 'update'])->name('update');
        Route::delete('/{roomBill}', [$class, 'destroy'])->name('destroy');
        Route::get('/{roomBill}/edit', [$class, 'edit'])->name('edit');
    });
});

resources/views/AdminPage/room_statuses/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create New Room Status') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('status.store') }}">
                        @csrf

                        {{-- <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Room</label>
                            <div class="col-md-6">
                                @foreach ($rooms as $room)
                                    <div class="form-check">
                                        <input type="radio" name="room_name" value="{{ $room->room_name }}">
                                        <label for="">{{ $room->room_name }}</label>
                                    </div>
                                @endforeach
                            </div>
                        </div> --}}

                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Select Room</label>
                            <div class="col-md-6">
                                <select name="room_id" class="form-select form-select-sm">
                                    @foreach ($rooms as $room)
                                        <option value="{{ $room->id }}">Room {{ $room->room_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Status</label>
                            <div class="col-md-6">
                                <div class="form-check">
                                    <input type="radio" name="status" value="0" checked>
                                    <label for="">Empty</label>
                                </div>
                                <div class="form-check">
                                    <input type="radio" name="status" value="1">
                                    <label for="">Active</label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Time') }}</label>
                            <div class="col-md-6">
                                <input id="time" value="{{ old('time') }}" name="time" type="date" class="form-control @error('time') is-invalid @enderror" >
                                @error('time')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/room_statuses/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Room Status {{$roomStatus->id}}</div>

                <div class="card-body">
                    <form action="{{ route('status.update', $roomStatus) }}" method="POST">

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Time</label>

                            <div class="col-md-6">
                                <input id="time" name="time" value="{{ $roomStatus->time }}" type="date" class="form-control @error('time') is-invalid @enderror" >
                                @error('time')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Select Room</label>
                            <div class="col-md-6">
                                <select name="room_id" class="form-select form-select-sm">
                                    @foreach ($rooms as $room)
                                        <option value="{{ $room->id }}"
                                        @if($room->id == $roomStatus->room_id) selected @endif> Room {{ $room->room_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Status</label>
                            <div class="col-md-6">
                                <div class="form-check">
                                    <input type="radio" name="status" value="0" @if($roomStatus->status == 0) checked @endif>
                                    <label for="">Empty</label>
                                </div>
                                <div class="form-check">
                                    <input type="radio" name="status" value="1" @if($roomStatus->status == 1) checked @endif>
                                    <label for="">Used</label>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/room_statuses/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">

        <div class="col-md-12">
            <h1 class="mt-4">Room's Status Management</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Welcome to Room's Status Management !!</li>
            </ol>
            <div class="card">
                <div class="card-header">
                    @receptionist
                    <a href="{{ route('status.create') }}" class="btn btn-primary">Create New Room's Status</a>
                    @endif
                </div>

                <form action="{{ route("status.index") }}" method="GET" class="md-3 d-flex">
                    <select name="room_id" class="form-select form-select-sm">
                        <option value="">Filter by Room</option>
                        @foreach ($rooms as $room)
                            <option value="{{ $room->id }}" {{ request('room_id') == $room->id ? "selected":"" }}> Room {{ $room->room_name }}</option>
                        @endforeach
                    </select>
                    <br>
                    <select name="filter_status" class="form-select form-select-sm">
                        <option value="">Filter by Status</option>
                        <option name="status" value="0" {{ request('filter_status') == '0' ? "selected":"" }}>Empty</option>
                        <option name="status" value="1" {{ request('filter_status') == '1' ? "selected":"" }}>Used</option>
                    </select>
                    <br>
                    <input type="date" class="form-control" placeholder="Enter time" name="key" value="{{ request('key') }}">
                    <br>
                    <input type="text" class="form-control" placeholder="Enter number per page" name="number" value="{{ request('number') }}">
                    <br>
                    <button type="submit" class="btn btn-success">Search</button>
                </form>
                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Room's Name</th>
                            <th scope="col">Status</th>
                            <th scope="col">Time</th>
                            @receptionist
                            <th scope="col">Actions</th>
                            @endif
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($roomStatus as $status)
                            <tr>
                                <th scope="row">{{$status->id}}</th>
                                <td>
                                    @foreach ($rooms as $room)
                                        @if($status->room_id == $room->id) {{$room->room_name}} @endif
                                    @endforeach
                                </td>
                                <td>
                                    @if($status->status == '0') Empty
                                    @else Used
                                    @endif
                                </td>
                                <td>{{$status->time}}</td>
                                @receptionist
                                <td>
                                    <a href="{{ route('status.show', $status->id) }}"><button type="button" class="btn btn-success">DETAIL</button></a>
                                    <a href="{{ route('status.edit', $status->id) }}"><button type="button" class="btn btn-warning">EDIT</button>
                                    <form action="{{ route('status.destroy', $status) }}" method="POST" class="float-left">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">DELETE</button>
                                    </form>
                                </td>
                                @endif
                              </tr>
                            @endforeach
                        </tbody>
                      </table>
                      {{$roomStatus->appends(request()->only('key','number','filter_status','room_id'))->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/AdminPage/room_statuses/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Room Status {{$roomStatus->id}}</div>

                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Room ID</th>
                            <th scope="col">Status</th>
                            <th scope="col">Time</th>
                          </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">{{$roomStatus->id}}</th>
                                <td>{{$roomStatus->room_id}}</td>
                                <td>{{$roomStatus->status}}</td>
                                <td>{{$roomStatus->time}}</td>
                              </tr>
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection